[postgresql]
source = "git"
git = "https://git.postgresql.org/git/postgresql.git"
prefix = "REL_"
exclude_regex = ".*(pre|a|alpha|b|beta|r|rc|RC|BETA|ALPHA).*"
include_regex = "REL_.+"
from_pattern = "([0-9]+)_([0-9]+)"
to_pattern = "\\1.\\2"
